/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.SeleniumStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SeleniumStandaloneSetup extends SeleniumStandaloneSetupGenerated {
  public static void doSetup() {
    new SeleniumStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
