/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.imt.selenium.ui.internal.SeleniumActivator;

public class SeleniumUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SeleniumActivator.getInstance().getInjector("org.xtext.example.mydsl.Selenium");
	}

}
