/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.SeleniumRuntimeModule;
import org.xtext.example.mydsl.SeleniumStandaloneSetup;
import org.xtext.example.mydsl.ide.SeleniumIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SeleniumIdeSetup extends SeleniumStandaloneSetup {
  @Override
  public Injector createInjector() {
    SeleniumRuntimeModule _seleniumRuntimeModule = new SeleniumRuntimeModule();
    SeleniumIdeModule _seleniumIdeModule = new SeleniumIdeModule();
    return Guice.createInjector(Modules2.mixin(_seleniumRuntimeModule, _seleniumIdeModule));
  }
}
