/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalSeleniumParser;
import org.xtext.example.mydsl.services.SeleniumGrammarAccess;

public class SeleniumParser extends AbstractAntlrParser {

	@Inject
	private SeleniumGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSeleniumParser createParser(XtextTokenStream stream) {
		return new InternalSeleniumParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Global";
	}

	public SeleniumGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SeleniumGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
