/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SeleniumGrammarAccess extends AbstractGrammarElementFinder {
	
	public class GlobalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.Global");
		private final Assignment cProgramsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cProgramsProgramParserRuleCall_0 = (RuleCall)cProgramsAssignment.eContents().get(0);
		
		//Global:
		//	programs+=Program*;
		@Override public ParserRule getRule() { return rule; }
		
		//programs+=Program*
		public Assignment getProgramsAssignment() { return cProgramsAssignment; }
		
		//Program
		public RuleCall getProgramsProgramParserRuleCall_0() { return cProgramsProgramParserRuleCall_0; }
	}
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cReturnsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRetAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cRetAlternatives_2_0 = (Alternatives)cRetAssignment_2.eContents().get(0);
		private final Keyword cRetTrueKeyword_2_0_0 = (Keyword)cRetAlternatives_2_0.eContents().get(0);
		private final Keyword cRetFalseKeyword_2_0_1 = (Keyword)cRetAlternatives_2_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cOpenKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cInsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cInsInstructionParserRuleCall_5_0 = (RuleCall)cInsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Program:
		//	name=ID "returns" ret=("true" | "false")
		//	"{"
		//	"open;"
		//	ins+=Instruction*
		//	"}";
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID "returns" ret=("true" | "false") "{" "open;" ins+=Instruction* "}"
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//"returns"
		public Keyword getReturnsKeyword_1() { return cReturnsKeyword_1; }
		
		//ret=("true" | "false")
		public Assignment getRetAssignment_2() { return cRetAssignment_2; }
		
		//("true" | "false")
		public Alternatives getRetAlternatives_2_0() { return cRetAlternatives_2_0; }
		
		//"true"
		public Keyword getRetTrueKeyword_2_0_0() { return cRetTrueKeyword_2_0_0; }
		
		//"false"
		public Keyword getRetFalseKeyword_2_0_1() { return cRetFalseKeyword_2_0_1; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//"open;"
		public Keyword getOpenKeyword_4() { return cOpenKeyword_4; }
		
		//ins+=Instruction*
		public Assignment getInsAssignment_5() { return cInsAssignment_5; }
		
		//Instruction
		public RuleCall getInsInstructionParserRuleCall_5_0() { return cInsInstructionParserRuleCall_5_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.Instruction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final RuleCall cGoParserRuleCall_0_0 = (RuleCall)cAlternatives_0.eContents().get(0);
		private final RuleCall cVerifyParserRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final RuleCall cClickParserRuleCall_0_2 = (RuleCall)cAlternatives_0.eContents().get(2);
		private final RuleCall cFillTextParserRuleCall_0_3 = (RuleCall)cAlternatives_0.eContents().get(3);
		private final RuleCall cCheckParserRuleCall_0_4 = (RuleCall)cAlternatives_0.eContents().get(4);
		private final RuleCall cSelectComboParserRuleCall_0_5 = (RuleCall)cAlternatives_0.eContents().get(5);
		private final RuleCall cVariableParserRuleCall_0_6 = (RuleCall)cAlternatives_0.eContents().get(6);
		private final Keyword cSemicolonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Instruction:
		//	(Go | Verify | Click | FillText | Check | SelectCombo | Variable) ";";
		@Override public ParserRule getRule() { return rule; }
		
		//(Go | Verify | Click | FillText | Check | SelectCombo | Variable) ";"
		public Group getGroup() { return cGroup; }
		
		//(Go | Verify | Click | FillText | Check | SelectCombo | Variable)
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//Go
		public RuleCall getGoParserRuleCall_0_0() { return cGoParserRuleCall_0_0; }
		
		//Verify
		public RuleCall getVerifyParserRuleCall_0_1() { return cVerifyParserRuleCall_0_1; }
		
		//Click
		public RuleCall getClickParserRuleCall_0_2() { return cClickParserRuleCall_0_2; }
		
		//FillText
		public RuleCall getFillTextParserRuleCall_0_3() { return cFillTextParserRuleCall_0_3; }
		
		//Check
		public RuleCall getCheckParserRuleCall_0_4() { return cCheckParserRuleCall_0_4; }
		
		//SelectCombo
		public RuleCall getSelectComboParserRuleCall_0_5() { return cSelectComboParserRuleCall_0_5; }
		
		//Variable
		public RuleCall getVariableParserRuleCall_0_6() { return cVariableParserRuleCall_0_6; }
		
		//";"
		public Keyword getSemicolonKeyword_1() { return cSemicolonKeyword_1; }
	}
	public class GoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.Go");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGotoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUrlAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUrlSTRINGTerminalRuleCall_1_0 = (RuleCall)cUrlAssignment_1.eContents().get(0);
		
		//Go:
		//	"goto:" url=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//"goto:" url=STRING
		public Group getGroup() { return cGroup; }
		
		//"goto:"
		public Keyword getGotoKeyword_0() { return cGotoKeyword_0; }
		
		//url=STRING
		public Assignment getUrlAssignment_1() { return cUrlAssignment_1; }
		
		//STRING
		public RuleCall getUrlSTRINGTerminalRuleCall_1_0() { return cUrlSTRINGTerminalRuleCall_1_0; }
	}
	public class VerifyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.Verify");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVerifyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cPageKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Assignment cElemAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final RuleCall cElemElementParserRuleCall_1_1_0 = (RuleCall)cElemAssignment_1_1.eContents().get(0);
		private final Keyword cContainsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cTextAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cTextSTRINGTerminalRuleCall_3_0_0 = (RuleCall)cTextAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cVarAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final CrossReference cVarVariableCrossReference_3_1_1_0 = (CrossReference)cVarAssignment_3_1_1.eContents().get(0);
		private final RuleCall cVarVariableIDTerminalRuleCall_3_1_1_0_1 = (RuleCall)cVarVariableCrossReference_3_1_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_3_1_2 = (Keyword)cGroup_3_1.eContents().get(2);
		private final Assignment cElementAssignment_3_2 = (Assignment)cAlternatives_3.eContents().get(2);
		private final RuleCall cElementElementParserRuleCall_3_2_0 = (RuleCall)cElementAssignment_3_2.eContents().get(0);
		
		//Verify:
		//	"verify:" ("page" | elem=Element) "contains" (text=STRING | "[" var=[Variable] "]" | Element=Element);
		@Override public ParserRule getRule() { return rule; }
		
		//"verify:" ("page" | elem=Element) "contains" (text=STRING | "[" var=[Variable] "]" | Element=Element)
		public Group getGroup() { return cGroup; }
		
		//"verify:"
		public Keyword getVerifyKeyword_0() { return cVerifyKeyword_0; }
		
		//("page" | elem=Element)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//"page"
		public Keyword getPageKeyword_1_0() { return cPageKeyword_1_0; }
		
		//elem=Element
		public Assignment getElemAssignment_1_1() { return cElemAssignment_1_1; }
		
		//Element
		public RuleCall getElemElementParserRuleCall_1_1_0() { return cElemElementParserRuleCall_1_1_0; }
		
		//"contains"
		public Keyword getContainsKeyword_2() { return cContainsKeyword_2; }
		
		//(text=STRING | "[" var=[Variable] "]" | Element=Element)
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//text=STRING
		public Assignment getTextAssignment_3_0() { return cTextAssignment_3_0; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_3_0_0() { return cTextSTRINGTerminalRuleCall_3_0_0; }
		
		//"[" var=[Variable] "]"
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_3_1_0() { return cLeftSquareBracketKeyword_3_1_0; }
		
		//var=[Variable]
		public Assignment getVarAssignment_3_1_1() { return cVarAssignment_3_1_1; }
		
		//[Variable]
		public CrossReference getVarVariableCrossReference_3_1_1_0() { return cVarVariableCrossReference_3_1_1_0; }
		
		//ID
		public RuleCall getVarVariableIDTerminalRuleCall_3_1_1_0_1() { return cVarVariableIDTerminalRuleCall_3_1_1_0_1; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_3_1_2() { return cRightSquareBracketKeyword_3_1_2; }
		
		//Element=Element
		public Assignment getElementAssignment_3_2() { return cElementAssignment_3_2; }
		
		//Element
		public RuleCall getElementElementParserRuleCall_3_2_0() { return cElementElementParserRuleCall_3_2_0; }
	}
	public class FillTextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.FillText");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFillKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cTextAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cTextSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cTextAssignment_1_0.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cVarAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final CrossReference cVarVariableCrossReference_1_1_1_0 = (CrossReference)cVarAssignment_1_1_1.eContents().get(0);
		private final RuleCall cVarVariableIDTerminalRuleCall_1_1_1_0_1 = (RuleCall)cVarVariableCrossReference_1_1_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_1_1_2 = (Keyword)cGroup_1_1.eContents().get(2);
		private final Keyword cInKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPropAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPropByPropertyParserRuleCall_3_0 = (RuleCall)cPropAssignment_3.eContents().get(0);
		private final Assignment cTargetAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTargetSTRINGTerminalRuleCall_4_0 = (RuleCall)cTargetAssignment_4.eContents().get(0);
		
		//FillText:
		//	"fill:" (text=STRING | "[" var=[Variable] "]") "in" prop=ByProperty target=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//"fill:" (text=STRING | "[" var=[Variable] "]") "in" prop=ByProperty target=STRING
		public Group getGroup() { return cGroup; }
		
		//"fill:"
		public Keyword getFillKeyword_0() { return cFillKeyword_0; }
		
		//(text=STRING | "[" var=[Variable] "]")
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//text=STRING
		public Assignment getTextAssignment_1_0() { return cTextAssignment_1_0; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_1_0_0() { return cTextSTRINGTerminalRuleCall_1_0_0; }
		
		//"[" var=[Variable] "]"
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_1_1_0() { return cLeftSquareBracketKeyword_1_1_0; }
		
		//var=[Variable]
		public Assignment getVarAssignment_1_1_1() { return cVarAssignment_1_1_1; }
		
		//[Variable]
		public CrossReference getVarVariableCrossReference_1_1_1_0() { return cVarVariableCrossReference_1_1_1_0; }
		
		//ID
		public RuleCall getVarVariableIDTerminalRuleCall_1_1_1_0_1() { return cVarVariableIDTerminalRuleCall_1_1_1_0_1; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_1_1_2() { return cRightSquareBracketKeyword_1_1_2; }
		
		//"in"
		public Keyword getInKeyword_2() { return cInKeyword_2; }
		
		//prop=ByProperty
		public Assignment getPropAssignment_3() { return cPropAssignment_3; }
		
		//ByProperty
		public RuleCall getPropByPropertyParserRuleCall_3_0() { return cPropByPropertyParserRuleCall_3_0; }
		
		//target=STRING
		public Assignment getTargetAssignment_4() { return cTargetAssignment_4; }
		
		//STRING
		public RuleCall getTargetSTRINGTerminalRuleCall_4_0() { return cTargetSTRINGTerminalRuleCall_4_0; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.Variable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Keyword cTextKeyword_3_0 = (Keyword)cAlternatives_3.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cPropertyKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cAttrAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cAttrSTRINGTerminalRuleCall_3_1_1_0 = (RuleCall)cAttrAssignment_3_1_1.eContents().get(0);
		private final Keyword cOfKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cElemAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cElemElementParserRuleCall_5_0 = (RuleCall)cElemAssignment_5.eContents().get(0);
		
		//Variable:
		//	"var" name=ID "=" ("text" | "property" attr=STRING) "of" elem=Element;
		@Override public ParserRule getRule() { return rule; }
		
		//"var" name=ID "=" ("text" | "property" attr=STRING) "of" elem=Element
		public Group getGroup() { return cGroup; }
		
		//"var"
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//("text" | "property" attr=STRING)
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//"text"
		public Keyword getTextKeyword_3_0() { return cTextKeyword_3_0; }
		
		//"property" attr=STRING
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//"property"
		public Keyword getPropertyKeyword_3_1_0() { return cPropertyKeyword_3_1_0; }
		
		//attr=STRING
		public Assignment getAttrAssignment_3_1_1() { return cAttrAssignment_3_1_1; }
		
		//STRING
		public RuleCall getAttrSTRINGTerminalRuleCall_3_1_1_0() { return cAttrSTRINGTerminalRuleCall_3_1_1_0; }
		
		//"of"
		public Keyword getOfKeyword_4() { return cOfKeyword_4; }
		
		//elem=Element
		public Assignment getElemAssignment_5() { return cElemAssignment_5; }
		
		//Element
		public RuleCall getElemElementParserRuleCall_5_0() { return cElemElementParserRuleCall_5_0; }
	}
	public class ClickElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.Click");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClickKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cElementParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Click:
		//	"click:" Element;
		@Override public ParserRule getRule() { return rule; }
		
		//"click:" Element
		public Group getGroup() { return cGroup; }
		
		//"click:"
		public Keyword getClickKeyword_0() { return cClickKeyword_0; }
		
		//Element
		public RuleCall getElementParserRuleCall_1() { return cElementParserRuleCall_1; }
	}
	public class CheckElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.Check");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCheckKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cAllKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Assignment cByAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cByByParserRuleCall_1_1_0_0 = (RuleCall)cByAssignment_1_1_0.eContents().get(0);
		private final Assignment cTargetAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cTargetSTRINGTerminalRuleCall_1_1_1_0 = (RuleCall)cTargetAssignment_1_1_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Keyword cOnKeyword_2_0 = (Keyword)cAlternatives_2.eContents().get(0);
		private final Keyword cOffKeyword_2_1 = (Keyword)cAlternatives_2.eContents().get(1);
		
		//Check:
		//	"check:" ("all" | by=By target=STRING) ("on" | "off");
		@Override public ParserRule getRule() { return rule; }
		
		//"check:" ("all" | by=By target=STRING) ("on" | "off")
		public Group getGroup() { return cGroup; }
		
		//"check:"
		public Keyword getCheckKeyword_0() { return cCheckKeyword_0; }
		
		//("all" | by=By target=STRING)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//"all"
		public Keyword getAllKeyword_1_0() { return cAllKeyword_1_0; }
		
		//by=By target=STRING
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//by=By
		public Assignment getByAssignment_1_1_0() { return cByAssignment_1_1_0; }
		
		//By
		public RuleCall getByByParserRuleCall_1_1_0_0() { return cByByParserRuleCall_1_1_0_0; }
		
		//target=STRING
		public Assignment getTargetAssignment_1_1_1() { return cTargetAssignment_1_1_1; }
		
		//STRING
		public RuleCall getTargetSTRINGTerminalRuleCall_1_1_1_0() { return cTargetSTRINGTerminalRuleCall_1_1_1_0; }
		
		//("on" | "off")
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//"on"
		public Keyword getOnKeyword_2_0() { return cOnKeyword_2_0; }
		
		//"off"
		public Keyword getOffKeyword_2_1() { return cOffKeyword_2_1; }
	}
	public class SelectComboElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.SelectCombo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSelectComboKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cByAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cByByParserRuleCall_1_0 = (RuleCall)cByAssignment_1.eContents().get(0);
		private final Assignment cTargetAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTargetSTRINGTerminalRuleCall_2_0 = (RuleCall)cTargetAssignment_2.eContents().get(0);
		
		//SelectCombo:
		//	"select-combo:" by=By target=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//"select-combo:" by=By target=STRING
		public Group getGroup() { return cGroup; }
		
		//"select-combo:"
		public Keyword getSelectComboKeyword_0() { return cSelectComboKeyword_0; }
		
		//by=By
		public Assignment getByAssignment_1() { return cByAssignment_1; }
		
		//By
		public RuleCall getByByParserRuleCall_1_0() { return cByByParserRuleCall_1_0; }
		
		//target=STRING
		public Assignment getTargetAssignment_2() { return cTargetAssignment_2; }
		
		//STRING
		public RuleCall getTargetSTRINGTerminalRuleCall_2_0() { return cTargetSTRINGTerminalRuleCall_2_0; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.Element");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeTypeParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cNKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cNumberAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cNumberINTTerminalRuleCall_1_1_0 = (RuleCall)cNumberAssignment_1_1.eContents().get(0);
		private final Keyword cWhereKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSelectorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSelectorByParserRuleCall_3_0 = (RuleCall)cSelectorAssignment_3.eContents().get(0);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Assignment cTargetAssignment_4_0 = (Assignment)cAlternatives_4.eContents().get(0);
		private final RuleCall cTargetSTRINGTerminalRuleCall_4_0_0 = (RuleCall)cTargetAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cAlternatives_4.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Assignment cVarAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final CrossReference cVarVariableCrossReference_4_1_1_0 = (CrossReference)cVarAssignment_4_1_1.eContents().get(0);
		private final RuleCall cVarVariableIDTerminalRuleCall_4_1_1_0_1 = (RuleCall)cVarVariableCrossReference_4_1_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_4_1_2 = (Keyword)cGroup_4_1.eContents().get(2);
		
		//Element:
		//	type=Type? ("n°" number=INT)? "where" selector=By (target=STRING | "[" var=[Variable] "]");
		@Override public ParserRule getRule() { return rule; }
		
		//type=Type? ("n°" number=INT)? "where" selector=By (target=STRING | "[" var=[Variable] "]")
		public Group getGroup() { return cGroup; }
		
		//type=Type?
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_0_0() { return cTypeTypeParserRuleCall_0_0; }
		
		//("n°" number=INT)?
		public Group getGroup_1() { return cGroup_1; }
		
		//"n°"
		public Keyword getNKeyword_1_0() { return cNKeyword_1_0; }
		
		//number=INT
		public Assignment getNumberAssignment_1_1() { return cNumberAssignment_1_1; }
		
		//INT
		public RuleCall getNumberINTTerminalRuleCall_1_1_0() { return cNumberINTTerminalRuleCall_1_1_0; }
		
		//"where"
		public Keyword getWhereKeyword_2() { return cWhereKeyword_2; }
		
		//selector=By
		public Assignment getSelectorAssignment_3() { return cSelectorAssignment_3; }
		
		//By
		public RuleCall getSelectorByParserRuleCall_3_0() { return cSelectorByParserRuleCall_3_0; }
		
		//(target=STRING | "[" var=[Variable] "]")
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//target=STRING
		public Assignment getTargetAssignment_4_0() { return cTargetAssignment_4_0; }
		
		//STRING
		public RuleCall getTargetSTRINGTerminalRuleCall_4_0_0() { return cTargetSTRINGTerminalRuleCall_4_0_0; }
		
		//"[" var=[Variable] "]"
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_4_1_0() { return cLeftSquareBracketKeyword_4_1_0; }
		
		//var=[Variable]
		public Assignment getVarAssignment_4_1_1() { return cVarAssignment_4_1_1; }
		
		//[Variable]
		public CrossReference getVarVariableCrossReference_4_1_1_0() { return cVarVariableCrossReference_4_1_1_0; }
		
		//ID
		public RuleCall getVarVariableIDTerminalRuleCall_4_1_1_0_1() { return cVarVariableIDTerminalRuleCall_4_1_1_0_1; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_4_1_2() { return cRightSquareBracketKeyword_4_1_2; }
	}
	public class ByElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.By");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTextKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final RuleCall cByPropertyParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//By:
		//	"text=" | ByProperty;
		@Override public ParserRule getRule() { return rule; }
		
		//"text=" | ByProperty
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"text="
		public Keyword getTextKeyword_0() { return cTextKeyword_0; }
		
		//ByProperty
		public RuleCall getByPropertyParserRuleCall_1() { return cByPropertyParserRuleCall_1; }
	}
	public class ByPropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.ByProperty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPropertyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPropertyAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPropertySTRINGTerminalRuleCall_1_0 = (RuleCall)cPropertyAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//ByProperty:
		//	"property" property+=STRING "=";
		@Override public ParserRule getRule() { return rule; }
		
		//"property" property+=STRING "="
		public Group getGroup() { return cGroup; }
		
		//"property"
		public Keyword getPropertyKeyword_0() { return cPropertyKeyword_0; }
		
		//property+=STRING
		public Assignment getPropertyAssignment_1() { return cPropertyAssignment_1; }
		
		//STRING
		public RuleCall getPropertySTRINGTerminalRuleCall_1_0() { return cPropertySTRINGTerminalRuleCall_1_0; }
		
		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Selenium.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cImageKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cLinkKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cButtonKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cAnythingKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		//Type:
		//	"image" | "link" | "button" | "anything";
		@Override public ParserRule getRule() { return rule; }
		
		//"image" | "link" | "button" | "anything"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"image"
		public Keyword getImageKeyword_0() { return cImageKeyword_0; }
		
		//"link"
		public Keyword getLinkKeyword_1() { return cLinkKeyword_1; }
		
		//"button"
		public Keyword getButtonKeyword_2() { return cButtonKeyword_2; }
		
		//"anything"
		public Keyword getAnythingKeyword_3() { return cAnythingKeyword_3; }
	}
	
	
	private final GlobalElements pGlobal;
	private final ProgramElements pProgram;
	private final InstructionElements pInstruction;
	private final GoElements pGo;
	private final VerifyElements pVerify;
	private final FillTextElements pFillText;
	private final VariableElements pVariable;
	private final ClickElements pClick;
	private final CheckElements pCheck;
	private final SelectComboElements pSelectCombo;
	private final ElementElements pElement;
	private final ByElements pBy;
	private final ByPropertyElements pByProperty;
	private final TypeElements pType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SeleniumGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pGlobal = new GlobalElements();
		this.pProgram = new ProgramElements();
		this.pInstruction = new InstructionElements();
		this.pGo = new GoElements();
		this.pVerify = new VerifyElements();
		this.pFillText = new FillTextElements();
		this.pVariable = new VariableElements();
		this.pClick = new ClickElements();
		this.pCheck = new CheckElements();
		this.pSelectCombo = new SelectComboElements();
		this.pElement = new ElementElements();
		this.pBy = new ByElements();
		this.pByProperty = new ByPropertyElements();
		this.pType = new TypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.Selenium".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Global:
	//	programs+=Program*;
	public GlobalElements getGlobalAccess() {
		return pGlobal;
	}
	
	public ParserRule getGlobalRule() {
		return getGlobalAccess().getRule();
	}
	
	//Program:
	//	name=ID "returns" ret=("true" | "false")
	//	"{"
	//	"open;"
	//	ins+=Instruction*
	//	"}";
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Instruction:
	//	(Go | Verify | Click | FillText | Check | SelectCombo | Variable) ";";
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//Go:
	//	"goto:" url=STRING;
	public GoElements getGoAccess() {
		return pGo;
	}
	
	public ParserRule getGoRule() {
		return getGoAccess().getRule();
	}
	
	//Verify:
	//	"verify:" ("page" | elem=Element) "contains" (text=STRING | "[" var=[Variable] "]" | Element=Element);
	public VerifyElements getVerifyAccess() {
		return pVerify;
	}
	
	public ParserRule getVerifyRule() {
		return getVerifyAccess().getRule();
	}
	
	//FillText:
	//	"fill:" (text=STRING | "[" var=[Variable] "]") "in" prop=ByProperty target=STRING;
	public FillTextElements getFillTextAccess() {
		return pFillText;
	}
	
	public ParserRule getFillTextRule() {
		return getFillTextAccess().getRule();
	}
	
	//Variable:
	//	"var" name=ID "=" ("text" | "property" attr=STRING) "of" elem=Element;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//Click:
	//	"click:" Element;
	public ClickElements getClickAccess() {
		return pClick;
	}
	
	public ParserRule getClickRule() {
		return getClickAccess().getRule();
	}
	
	//Check:
	//	"check:" ("all" | by=By target=STRING) ("on" | "off");
	public CheckElements getCheckAccess() {
		return pCheck;
	}
	
	public ParserRule getCheckRule() {
		return getCheckAccess().getRule();
	}
	
	//SelectCombo:
	//	"select-combo:" by=By target=STRING;
	public SelectComboElements getSelectComboAccess() {
		return pSelectCombo;
	}
	
	public ParserRule getSelectComboRule() {
		return getSelectComboAccess().getRule();
	}
	
	//Element:
	//	type=Type? ("n°" number=INT)? "where" selector=By (target=STRING | "[" var=[Variable] "]");
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//By:
	//	"text=" | ByProperty;
	public ByElements getByAccess() {
		return pBy;
	}
	
	public ParserRule getByRule() {
		return getByAccess().getRule();
	}
	
	//ByProperty:
	//	"property" property+=STRING "=";
	public ByPropertyElements getByPropertyAccess() {
		return pByProperty;
	}
	
	public ParserRule getByPropertyRule() {
		return getByPropertyAccess().getRule();
	}
	
	//Type:
	//	"image" | "link" | "button" | "anything";
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
