/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.SeleniumGrammarAccess;

@SuppressWarnings("all")
public class SeleniumSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SeleniumGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Check_OffKeyword_2_1_or_OnKeyword_2_0;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SeleniumGrammarAccess) access;
		match_Check_OffKeyword_2_1_or_OnKeyword_2_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getCheckAccess().getOffKeyword_2_1()), new TokenAlias(false, false, grammarAccess.getCheckAccess().getOnKeyword_2_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Check_OffKeyword_2_1_or_OnKeyword_2_0.equals(syntax))
				emit_Check_OffKeyword_2_1_or_OnKeyword_2_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'on' | 'off'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'check:' 'all' (ambiguity) ';' (rule start)
	 *     (rule start) 'check:' 'all' (ambiguity) (rule start)
	 *     target=STRING (ambiguity) ';' (rule end)
	 *     target=STRING (ambiguity) (rule end)
	 */
	protected void emit_Check_OffKeyword_2_1_or_OnKeyword_2_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
