/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.selenium;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>By</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.selenium.SeleniumPackage#getBy()
 * @model
 * @generated
 */
public interface By extends EObject
{
} // By
