/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.selenium;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>By Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.selenium.ByProperty#getProperty <em>Property</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.selenium.SeleniumPackage#getByProperty()
 * @model
 * @generated
 */
public interface ByProperty extends By
{
  /**
   * Returns the value of the '<em><b>Property</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' attribute list.
   * @see org.xtext.example.mydsl.selenium.SeleniumPackage#getByProperty_Property()
   * @model unique="false"
   * @generated
   */
  EList<String> getProperty();

} // ByProperty
