/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.selenium;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Global</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.selenium.Global#getPrograms <em>Programs</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.selenium.SeleniumPackage#getGlobal()
 * @model
 * @generated
 */
public interface Global extends EObject
{
  /**
   * Returns the value of the '<em><b>Programs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.selenium.Program}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Programs</em>' containment reference list.
   * @see org.xtext.example.mydsl.selenium.SeleniumPackage#getGlobal_Programs()
   * @model containment="true"
   * @generated
   */
  EList<Program> getPrograms();

} // Global
