/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.selenium;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.selenium.Program#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.selenium.Program#getRet <em>Ret</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.selenium.Program#getIns <em>Ins</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.selenium.SeleniumPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.selenium.SeleniumPackage#getProgram_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.selenium.Program#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ret</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ret</em>' attribute.
   * @see #setRet(String)
   * @see org.xtext.example.mydsl.selenium.SeleniumPackage#getProgram_Ret()
   * @model
   * @generated
   */
  String getRet();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.selenium.Program#getRet <em>Ret</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ret</em>' attribute.
   * @see #getRet()
   * @generated
   */
  void setRet(String value);

  /**
   * Returns the value of the '<em><b>Ins</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.selenium.Instruction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ins</em>' containment reference list.
   * @see org.xtext.example.mydsl.selenium.SeleniumPackage#getProgram_Ins()
   * @model containment="true"
   * @generated
   */
  EList<Instruction> getIns();

} // Program
