/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.selenium;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.selenium.SeleniumFactory
 * @model kind="package"
 * @generated
 */
public interface SeleniumPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "selenium";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Selenium";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "selenium";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SeleniumPackage eINSTANCE = org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.GlobalImpl <em>Global</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.GlobalImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getGlobal()
   * @generated
   */
  int GLOBAL = 0;

  /**
   * The feature id for the '<em><b>Programs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOBAL__PROGRAMS = 0;

  /**
   * The number of structural features of the '<em>Global</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOBAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.ProgramImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Ret</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__RET = 1;

  /**
   * The feature id for the '<em><b>Ins</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__INS = 2;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.InstructionImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 2;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.GoImpl <em>Go</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.GoImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getGo()
   * @generated
   */
  int GO = 3;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO__URL = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Go</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.VerifyImpl <em>Verify</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.VerifyImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getVerify()
   * @generated
   */
  int VERIFY = 4;

  /**
   * The feature id for the '<em><b>Elem</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__ELEM = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__TEXT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__VAR = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__ELEMENT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Verify</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.FillTextImpl <em>Fill Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.FillTextImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getFillText()
   * @generated
   */
  int FILL_TEXT = 5;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_TEXT__TEXT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_TEXT__VAR = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Prop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_TEXT__PROP = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_TEXT__TARGET = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Fill Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_TEXT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.VariableImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Attr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__ATTR = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Elem</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__ELEM = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.ClickImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getClick()
   * @generated
   */
  int CLICK = 7;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.CheckImpl <em>Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.CheckImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getCheck()
   * @generated
   */
  int CHECK = 8;

  /**
   * The feature id for the '<em><b>By</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__BY = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__TARGET = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.SelectComboImpl <em>Select Combo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.SelectComboImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getSelectCombo()
   * @generated
   */
  int SELECT_COMBO = 9;

  /**
   * The feature id for the '<em><b>By</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COMBO__BY = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COMBO__TARGET = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Select Combo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COMBO_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.ElementImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 10;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__TYPE = CLICK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NUMBER = CLICK_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__SELECTOR = CLICK_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__TARGET = CLICK_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__VAR = CLICK_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = CLICK_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.ByImpl <em>By</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.ByImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getBy()
   * @generated
   */
  int BY = 11;

  /**
   * The number of structural features of the '<em>By</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BY_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.selenium.impl.ByPropertyImpl <em>By Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.selenium.impl.ByPropertyImpl
   * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getByProperty()
   * @generated
   */
  int BY_PROPERTY = 12;

  /**
   * The feature id for the '<em><b>Property</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BY_PROPERTY__PROPERTY = BY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>By Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BY_PROPERTY_FEATURE_COUNT = BY_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.Global <em>Global</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Global</em>'.
   * @see org.xtext.example.mydsl.selenium.Global
   * @generated
   */
  EClass getGlobal();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.selenium.Global#getPrograms <em>Programs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Programs</em>'.
   * @see org.xtext.example.mydsl.selenium.Global#getPrograms()
   * @see #getGlobal()
   * @generated
   */
  EReference getGlobal_Programs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.mydsl.selenium.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.Program#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.selenium.Program#getName()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.Program#getRet <em>Ret</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ret</em>'.
   * @see org.xtext.example.mydsl.selenium.Program#getRet()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_Ret();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.selenium.Program#getIns <em>Ins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ins</em>'.
   * @see org.xtext.example.mydsl.selenium.Program#getIns()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Ins();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.xtext.example.mydsl.selenium.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.Go <em>Go</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Go</em>'.
   * @see org.xtext.example.mydsl.selenium.Go
   * @generated
   */
  EClass getGo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.Go#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.mydsl.selenium.Go#getUrl()
   * @see #getGo()
   * @generated
   */
  EAttribute getGo_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.Verify <em>Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verify</em>'.
   * @see org.xtext.example.mydsl.selenium.Verify
   * @generated
   */
  EClass getVerify();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.selenium.Verify#getElem <em>Elem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elem</em>'.
   * @see org.xtext.example.mydsl.selenium.Verify#getElem()
   * @see #getVerify()
   * @generated
   */
  EReference getVerify_Elem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.Verify#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.mydsl.selenium.Verify#getText()
   * @see #getVerify()
   * @generated
   */
  EAttribute getVerify_Text();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.selenium.Verify#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see org.xtext.example.mydsl.selenium.Verify#getVar()
   * @see #getVerify()
   * @generated
   */
  EReference getVerify_Var();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.selenium.Verify#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see org.xtext.example.mydsl.selenium.Verify#getElement()
   * @see #getVerify()
   * @generated
   */
  EReference getVerify_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.FillText <em>Fill Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fill Text</em>'.
   * @see org.xtext.example.mydsl.selenium.FillText
   * @generated
   */
  EClass getFillText();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.FillText#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.mydsl.selenium.FillText#getText()
   * @see #getFillText()
   * @generated
   */
  EAttribute getFillText_Text();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.selenium.FillText#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see org.xtext.example.mydsl.selenium.FillText#getVar()
   * @see #getFillText()
   * @generated
   */
  EReference getFillText_Var();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.selenium.FillText#getProp <em>Prop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prop</em>'.
   * @see org.xtext.example.mydsl.selenium.FillText#getProp()
   * @see #getFillText()
   * @generated
   */
  EReference getFillText_Prop();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.FillText#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.xtext.example.mydsl.selenium.FillText#getTarget()
   * @see #getFillText()
   * @generated
   */
  EAttribute getFillText_Target();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.example.mydsl.selenium.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.selenium.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.Variable#getAttr <em>Attr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attr</em>'.
   * @see org.xtext.example.mydsl.selenium.Variable#getAttr()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Attr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.selenium.Variable#getElem <em>Elem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elem</em>'.
   * @see org.xtext.example.mydsl.selenium.Variable#getElem()
   * @see #getVariable()
   * @generated
   */
  EReference getVariable_Elem();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see org.xtext.example.mydsl.selenium.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.Check <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check</em>'.
   * @see org.xtext.example.mydsl.selenium.Check
   * @generated
   */
  EClass getCheck();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.selenium.Check#getBy <em>By</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>By</em>'.
   * @see org.xtext.example.mydsl.selenium.Check#getBy()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_By();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.Check#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.xtext.example.mydsl.selenium.Check#getTarget()
   * @see #getCheck()
   * @generated
   */
  EAttribute getCheck_Target();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.SelectCombo <em>Select Combo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Combo</em>'.
   * @see org.xtext.example.mydsl.selenium.SelectCombo
   * @generated
   */
  EClass getSelectCombo();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.selenium.SelectCombo#getBy <em>By</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>By</em>'.
   * @see org.xtext.example.mydsl.selenium.SelectCombo#getBy()
   * @see #getSelectCombo()
   * @generated
   */
  EReference getSelectCombo_By();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.SelectCombo#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.xtext.example.mydsl.selenium.SelectCombo#getTarget()
   * @see #getSelectCombo()
   * @generated
   */
  EAttribute getSelectCombo_Target();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.mydsl.selenium.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.Element#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.selenium.Element#getType()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.Element#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.example.mydsl.selenium.Element#getNumber()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Number();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.selenium.Element#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see org.xtext.example.mydsl.selenium.Element#getSelector()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Selector();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.selenium.Element#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.xtext.example.mydsl.selenium.Element#getTarget()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Target();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.selenium.Element#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see org.xtext.example.mydsl.selenium.Element#getVar()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.By <em>By</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>By</em>'.
   * @see org.xtext.example.mydsl.selenium.By
   * @generated
   */
  EClass getBy();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.selenium.ByProperty <em>By Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>By Property</em>'.
   * @see org.xtext.example.mydsl.selenium.ByProperty
   * @generated
   */
  EClass getByProperty();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.selenium.ByProperty#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Property</em>'.
   * @see org.xtext.example.mydsl.selenium.ByProperty#getProperty()
   * @see #getByProperty()
   * @generated
   */
  EAttribute getByProperty_Property();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SeleniumFactory getSeleniumFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.GlobalImpl <em>Global</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.GlobalImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getGlobal()
     * @generated
     */
    EClass GLOBAL = eINSTANCE.getGlobal();

    /**
     * The meta object literal for the '<em><b>Programs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GLOBAL__PROGRAMS = eINSTANCE.getGlobal_Programs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.ProgramImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__NAME = eINSTANCE.getProgram_Name();

    /**
     * The meta object literal for the '<em><b>Ret</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__RET = eINSTANCE.getProgram_Ret();

    /**
     * The meta object literal for the '<em><b>Ins</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__INS = eINSTANCE.getProgram_Ins();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.InstructionImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.GoImpl <em>Go</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.GoImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getGo()
     * @generated
     */
    EClass GO = eINSTANCE.getGo();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GO__URL = eINSTANCE.getGo_Url();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.VerifyImpl <em>Verify</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.VerifyImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getVerify()
     * @generated
     */
    EClass VERIFY = eINSTANCE.getVerify();

    /**
     * The meta object literal for the '<em><b>Elem</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERIFY__ELEM = eINSTANCE.getVerify_Elem();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERIFY__TEXT = eINSTANCE.getVerify_Text();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERIFY__VAR = eINSTANCE.getVerify_Var();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERIFY__ELEMENT = eINSTANCE.getVerify_Element();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.FillTextImpl <em>Fill Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.FillTextImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getFillText()
     * @generated
     */
    EClass FILL_TEXT = eINSTANCE.getFillText();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL_TEXT__TEXT = eINSTANCE.getFillText_Text();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILL_TEXT__VAR = eINSTANCE.getFillText_Var();

    /**
     * The meta object literal for the '<em><b>Prop</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILL_TEXT__PROP = eINSTANCE.getFillText_Prop();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL_TEXT__TARGET = eINSTANCE.getFillText_Target();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.VariableImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '<em><b>Attr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__ATTR = eINSTANCE.getVariable_Attr();

    /**
     * The meta object literal for the '<em><b>Elem</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE__ELEM = eINSTANCE.getVariable_Elem();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.ClickImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.CheckImpl <em>Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.CheckImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getCheck()
     * @generated
     */
    EClass CHECK = eINSTANCE.getCheck();

    /**
     * The meta object literal for the '<em><b>By</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__BY = eINSTANCE.getCheck_By();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK__TARGET = eINSTANCE.getCheck_Target();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.SelectComboImpl <em>Select Combo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.SelectComboImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getSelectCombo()
     * @generated
     */
    EClass SELECT_COMBO = eINSTANCE.getSelectCombo();

    /**
     * The meta object literal for the '<em><b>By</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_COMBO__BY = eINSTANCE.getSelectCombo_By();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_COMBO__TARGET = eINSTANCE.getSelectCombo_Target();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.ElementImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__TYPE = eINSTANCE.getElement_Type();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NUMBER = eINSTANCE.getElement_Number();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__SELECTOR = eINSTANCE.getElement_Selector();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__TARGET = eINSTANCE.getElement_Target();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__VAR = eINSTANCE.getElement_Var();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.ByImpl <em>By</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.ByImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getBy()
     * @generated
     */
    EClass BY = eINSTANCE.getBy();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.selenium.impl.ByPropertyImpl <em>By Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.selenium.impl.ByPropertyImpl
     * @see org.xtext.example.mydsl.selenium.impl.SeleniumPackageImpl#getByProperty()
     * @generated
     */
    EClass BY_PROPERTY = eINSTANCE.getByProperty();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BY_PROPERTY__PROPERTY = eINSTANCE.getByProperty_Property();

  }

} //SeleniumPackage
