/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.selenium.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.selenium.By;
import org.xtext.example.mydsl.selenium.SeleniumPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>By</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ByImpl extends MinimalEObjectImpl.Container implements By
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ByImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SeleniumPackage.Literals.BY;
  }

} //ByImpl
