/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SeleniumStandaloneSetup extends SeleniumStandaloneSetupGenerated {

	def static void doSetup() {
		new SeleniumStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
