/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.imt.selenium.ui.internal.SeleniumActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SeleniumExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SeleniumActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SeleniumActivator activator = SeleniumActivator.getInstance();
		return activator != null ? activator.getInjector(SeleniumActivator.ORG_XTEXT_EXAMPLE_MYDSL_SELENIUM) : null;
	}

}
