/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.mydsl.ui.AbstractSeleniumUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SeleniumUiModule extends AbstractSeleniumUiModule {
  public SeleniumUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
